apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: service-api
spec:
 template:
  spec:
   containers:
    - image: jonnyman9/python39-diss-service@sha256:e61e5cf1f9cb03752011e0dbfdbdaa162a658fe412048eace7c63f20aeeac084
      ports:
        - containerPort: 3000
