apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base
patches:
  - data.yaml
patchesJson6902:
  - target:
      group: serving.knative.dev
      version: v1
      kind: Service
      name: service-api
    path: name-patch.yaml
