apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: service-api
spec:
 template:
  spec:
   containers:
    - image: jonnyman9/python38-diss-service@sha256:e907645f98fdfaddcdafb779cb08edd74719644f3d2235b35df135d18b54b23c
      ports:
        - containerPort: 3000
