apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: service-api
spec:
 template:
  spec:
   containers:
    - image: jonnyman9/python38-diss-service@sha256:a1342f5843b60b8e0b3a2160bfbd65e10898dbea291198e76267a90a4c7b88df
      ports:
        - containerPort: 3000
